name:                time-framework
version:             0.0.1
github:              "xsoufiane/time-framework"
license:             BSD3
author:              "Soufiane Maguerra"
maintainer:          "soufiane.maguerra@commercetools.com"
copyright:           "2021 Soufiane Maguerra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xsoufiane/time-framework#readme>

dependencies:
- base >= 4.7 && < 5
- either
- refined
- singletons
- template-haskell
- QuickCheck
- smallcheck
- tasty
- tasty-smallcheck

library:
  source-dirs: src
  exposed-modules:
  - Data.Time
  - Data.Chronon
  - Data.Period
  - Data.Period.PeriodChrononObs
  - Data.Period.PeriodObs
  - Data.Period.DifferentPeriodObs
  - Relation.Identity
  - Relation.Order
  - Structure.Identity
  - Structure.Identity.Laws
  - Structure.Order.StrictPartialOrder
  - Structure.Order.StrictPartialOrder.Laws
  - Structure.Order.LinearOrder
  - Structure.Order.LinearOrder.Laws
  - Structure.Order.LeftLinearOrder
  - Structure.Order.LeftLinearOrder.Laws
  - Structure.Order.RightLinearOrder
  - Structure.Order.RightLinearOrder.Laws
  - Structure.Order.PartialCyclicOrder
  - Structure.Order.PartialCyclicOrder.Laws
  - Structure.Order.CyclicOrder
  - Structure.Order.CyclicOrder.Laws
  - Structure.Order.PartialOrder
  - Structure.Order.PartialOrder.Laws
  - Structure.Order.TotalOrder
  - Structure.Order.TotalOrder.Laws
  - Structure.Order.Synchronicity
  - Structure.Order.Synchronicity.Laws
  - Structure.Order.Synchronicity.LinearOrder.Laws
  - Structure.Order.Synchronicity.Concurrency.Laws
  - Structure.Order.Concurrency
  - Structure.Order.Concurrency.Laws
  - Structure.Order.Concurrency.LinearOrder.Laws
  - Structure.Order.Betweenness
  - Structure.Order.Betweenness.Laws
  - Structure.Order.Begin
  - Structure.Order.Begin.Laws
  - Structure.Order.Begin.LinearOrder.Laws
  - Structure.Order.End
  - Structure.Order.End.Laws
  - Structure.Order.End.LinearOrder.Laws

tests:
  time-framework-spec:
    main: Spec.hs
    source-dirs:
    - test/spec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - time-framework
    - QuickCheck
    - quickcheck-classes
    - smallcheck
    - tasty
    - tasty-quickcheck
    - tasty-smallcheck
    - string-interpolate
